Browser/_Event/Server/StompTest/Test.ts(55,32): error TS2345: Argument of type '{ endpoint: string; }' is not assignable to parameter of type 'IOptions'. Object literal may only specify known properties, and 'endpoint' does not exist in type 'IOptions'. https://online.sbis.ru/opendoc.html?guid=c6e60fd3-60e9-40a6-a77c-b00ec433fd77