(3) Can't use unknown options by default because of modules in another repos: SBIS3CONTROLSUnit/_display/Collection.test.ts(4070,52): error TS2339: Property 'filter' does not exist on type 'unknown' SBIS3CONTROLSUnit/_display/Collection.test.ts(4070,52): error TS2339: Property 'filter' does not exist on type 'unknown'